services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=pubsub_project.settings
      
    command: daphne -b 0.0.0.0 -p 8000 pubsub_project.asgi:application

