# Generated by Django 4.2.7 on 2025-08-28 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pubsub_connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_published', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pubsub_topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pubsub.connection')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pubsub.topic')),
            ],
            options={
                'db_table': 'pubsub_topic_subscriptions',
                'ordering': ['-subscribed_at'],
                'unique_together': {('connection', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('max_delivery_attempts', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('publisher_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_messages', to='pubsub.connection')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pubsub.topic')),
            ],
            options={
                'db_table': 'pubsub_messages',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['topic', 'published_at'], name='pubsub_mess_topic_i_751eff_idx'), models.Index(fields=['publisher_connection', 'published_at'], name='pubsub_mess_publish_ce02a7_idx')],
            },
        ),
    ]
